# Generated by Django 3.1 on 2020-10-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200929_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='img_url',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
