# Generated by Django 3.0.4 on 2020-10-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201007_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.TextField(default='/static/images/icons/user.svg'),
        ),
    ]
