# Generated by Django 3.0.4 on 2020-10-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201019_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
