# Generated by Django 3.0.4 on 2020-10-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_share_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
