# Generated by Django 3.0.4 on 2020-10-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_share_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='shares',
            field=models.ManyToManyField(blank=True, to='main.Share'),
        ),
    ]
