# Generated by Django 3.0.4 on 2020-10-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bag_shares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchased_Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Share')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AlterField(
            model_name='bag',
            name='shares',
            field=models.ManyToManyField(blank=True, to='main.Purchased_Share'),
        ),
    ]
