# Generated by Django 3.0.4 on 2020-10-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201023_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='index',
            field=models.TextField(default=''),
        ),
    ]
