# Generated by Django 3.0.4 on 2020-10-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201012_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_on_shop',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
