# Generated by Django 3.0.4 on 2020-10-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_url',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Image'),
        ),
    ]
