# Generated by Django 3.0.4 on 2020-10-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_product_count_on_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
