# Generated by Django 3.0.4 on 2020-10-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='absolute_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='absolute_path',
            field=models.TextField(default=''),
        ),
    ]
