# Generated by Django 3.0.4 on 2020-10-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201028_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_type',
            field=models.TextField(default=''),
        ),
    ]
