# Generated by Django 3.0.4 on 2020-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_image_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchased_shares',
            field=models.ManyToManyField(blank=True, to='main.Purchased_Share'),
        ),
    ]
