# Generated by Django 3.0.4 on 2020-10-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='products',
            field=models.ManyToManyField(blank=True, to='main.Purchased_Product'),
        ),
    ]
