# Generated by Django 3.0.4 on 2020-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_purchase_purchased_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
