# Generated by Django 3.0.4 on 2020-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201013_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
