# Generated by Django 3.0.4 on 2020-10-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_purchase_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_price',
        ),
    ]
