# Generated by Django 3.0.4 on 2020-10-14 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rating_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
